build: FORCE
	flutter build web

build-web-release:
	flutter build web --release --base-href /app/

run-web:
	flutter run -d chrome --web-port 33337

run-web-tt:
	flutter run -d chrome --web-port 33337 --dart-define BACKEND=https://toutizes.com

run-ios-simulator-pro15:
	flutter run -d "iPhone 15 Pro Max"

run-ios-simulator-pro15-tt:
	flutter run -d "iPhone 15 Pro Max" --dart-define BACKEND=https://toutizes.com

run-pixel8:
	flutter run -d 3A101FDJH0099F

run-pixel8-tt:
	flutter run -d 3A101FDJH0099F --dart-define BACKEND=https://toutizes.com


launch-emulator:
	flutter emulators --launch Apple

FORCE:
