build: FORCE
	flutter build web

run-web:
	flutter run -d chrome --web-port 33337

run-ios-simulator-pro15:
	flutter run -d "iPhone 15 Pro Max"

launch-emulator:
	flutter emulators --launch Apple

FORCE:
