// Code generated by protoc-gen-go.
// source: db.proto
// DO NOT EDIT!

/*
Package store is a generated protocol buffer package.

It is generated from these files:
	db.proto

It has these top-level messages:
	Stereo
	Image
	Video
	Item
	Directory
*/
package store

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Stereo struct {
	Dx               *float32 `protobuf:"fixed32,1,opt,name=dx" json:"dx,omitempty"`
	Dy               *float32 `protobuf:"fixed32,2,opt,name=dy" json:"dy,omitempty"`
	AnaDx            *float32 `protobuf:"fixed32,3,opt,name=ana_dx" json:"ana_dx,omitempty"`
	AnaDy            *float32 `protobuf:"fixed32,4,opt,name=ana_dy" json:"ana_dy,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Stereo) Reset()         { *m = Stereo{} }
func (m *Stereo) String() string { return proto.CompactTextString(m) }
func (*Stereo) ProtoMessage()    {}

func (m *Stereo) GetDx() float32 {
	if m != nil && m.Dx != nil {
		return *m.Dx
	}
	return 0
}

func (m *Stereo) GetDy() float32 {
	if m != nil && m.Dy != nil {
		return *m.Dy
	}
	return 0
}

func (m *Stereo) GetAnaDx() float32 {
	if m != nil && m.AnaDx != nil {
		return *m.AnaDx
	}
	return 0
}

func (m *Stereo) GetAnaDy() float32 {
	if m != nil && m.AnaDy != nil {
		return *m.AnaDy
	}
	return 0
}

type Image struct {
	RotateDegrees    *int32  `protobuf:"varint,2,opt,name=rotate_degrees,def=0" json:"rotate_degrees,omitempty"`
	Stereo           *Stereo `protobuf:"bytes,3,opt,name=stereo" json:"stereo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}

const Default_Image_RotateDegrees int32 = 0

func (m *Image) GetRotateDegrees() int32 {
	if m != nil && m.RotateDegrees != nil {
		return *m.RotateDegrees
	}
	return Default_Image_RotateDegrees
}

func (m *Image) GetStereo() *Stereo {
	if m != nil {
		return m.Stereo
	}
	return nil
}

type Video struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}

type Item struct {
	Name          *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FileTimestamp *int64   `protobuf:"varint,2,opt,name=file_timestamp" json:"file_timestamp,omitempty"`
	ItemTimestamp *int64   `protobuf:"varint,3,opt,name=item_timestamp" json:"item_timestamp,omitempty"`
	Keywords      []string `protobuf:"bytes,4,rep,name=keywords" json:"keywords,omitempty"`
	// Use these as low overhead extensions.
	Image            *Image `protobuf:"bytes,100,opt,name=image" json:"image,omitempty"`
	Video            *Video `protobuf:"bytes,101,opt,name=video" json:"video,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}

func (m *Item) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Item) GetFileTimestamp() int64 {
	if m != nil && m.FileTimestamp != nil {
		return *m.FileTimestamp
	}
	return 0
}

func (m *Item) GetItemTimestamp() int64 {
	if m != nil && m.ItemTimestamp != nil {
		return *m.ItemTimestamp
	}
	return 0
}

func (m *Item) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *Item) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Item) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

type Directory struct {
	DirectoryTimestamp *int64   `protobuf:"varint,4,opt,name=directory_timestamp" json:"directory_timestamp,omitempty"`
	OrderBy            *string  `protobuf:"bytes,5,opt,name=order_by" json:"order_by,omitempty"`
	Items              []*Item  `protobuf:"bytes,6,rep,name=items" json:"items,omitempty"`
	SubDirectories     []string `protobuf:"bytes,7,rep,name=sub_directories" json:"sub_directories,omitempty"`
	XXX_unrecognized   []byte   `json:"-"`
}

func (m *Directory) Reset()         { *m = Directory{} }
func (m *Directory) String() string { return proto.CompactTextString(m) }
func (*Directory) ProtoMessage()    {}

func (m *Directory) GetDirectoryTimestamp() int64 {
	if m != nil && m.DirectoryTimestamp != nil {
		return *m.DirectoryTimestamp
	}
	return 0
}

func (m *Directory) GetOrderBy() string {
	if m != nil && m.OrderBy != nil {
		return *m.OrderBy
	}
	return ""
}

func (m *Directory) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Directory) GetSubDirectories() []string {
	if m != nil {
		return m.SubDirectories
	}
	return nil
}

func init() {
}
