// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYv45ZFi0WMZvSv9WbNc8RAuknm5SrqG8',
    appId: '1:347191427262:web:a229801596c62878a39eef',
    messagingSenderId: '347191427262',
    projectId: 'floutizes',
    authDomain: 'floutizes.firebaseapp.com',
    storageBucket: 'floutizes.firebasestorage.app',
    measurementId: 'G-D6EBFYBT5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmoCKYKZ8NFE5mPCDr_rptoAdE5haVNa8',
    appId: '1:347191427262:android:cabff8be970fbc85a39eef',
    messagingSenderId: '347191427262',
    projectId: 'floutizes',
    storageBucket: 'floutizes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyh2pC_shf2MtoUcc7URwAm0LppWQTF2U',
    appId: '1:347191427262:ios:35f81388b849e00fa39eef',
    messagingSenderId: '347191427262',
    projectId: 'floutizes',
    storageBucket: 'floutizes.firebasestorage.app',
    iosClientId: '347191427262-1i2b0dhk74duqt9oaib6prs6fv6q9jds.apps.googleusercontent.com',
    iosBundleId: 'com.example.floutizes',
  );

}